#!/usr/bin/env bash
# Devcontainer Commands - Generate .devcontainer config for VS Code
# ============================================================================
# Commands: devcontainer
# Generates .devcontainer/devcontainer.json plus VS Code tasks and launch
# configs referencing the ClaudeBox image

# Helper: collect profile-aware VS Code extension IDs into $extensions
_devcontainer_build_extensions() {
    local profiles="$1"
    extensions=""

    # Always useful inside a container
    extensions="\"ms-azuretools.vscode-docker\""

    local _check
    for _check in \
        "python:ms-python.python,ms-python.vscode-pylance" \
        "rust:rust-lang.rust-analyzer" \
        "go:golang.go" \
        "javascript:dbaeumer.vscode-eslint,esbenp.prettier-vscode" \
        "java:vscjava.vscode-java-pack" \
        "php:bmewburn.vscode-intelephense-client" \
        "ruby:shopify.ruby-lsp" \
        "flutter:Dart-Code.flutter,Dart-Code.dart-code" \
        "devops:hashicorp.terraform,ms-kubernetes-tools.vscode-kubernetes-tools" \
        "embedded:ms-vscode.cpptools" \
        "database:mtxr.sqltools"
    do
        local profile_key="${_check%%:*}"
        local ext_ids="${_check#*:}"

        if printf '%s' "$profiles" | grep -qw "$profile_key"; then
            # ext_ids is comma-separated; wrap each in quotes
            local IFS=","
            for eid in $ext_ids; do
                extensions="$extensions,
        \"$eid\""
            done
            unset IFS
        fi
    done

    # C profile needs word-boundary check (avoid matching "cache" etc.)
    if printf '%s' "$profiles" | grep -qE '(^|, )c(,|$)'; then
        extensions="$extensions,
        \"ms-vscode.cpptools\""
    fi
}

# Helper: gather comma-separated profile list for the current project
_devcontainer_gather_profiles() {
    current_profiles=""
    if [[ -n "${PROJECT_PARENT_DIR:-}" ]]; then
        local profiles_file="$PROJECT_PARENT_DIR/profiles.ini"
        if [[ -f "$profiles_file" ]]; then
            while IFS= read -r line; do
                if [[ -n "$line" ]]; then
                    if [[ -n "$current_profiles" ]]; then
                        current_profiles="$current_profiles, $line"
                    else
                        current_profiles="$line"
                    fi
                fi
            done < <(read_profile_section "$profiles_file" "profiles")
        fi
    fi
}

# ---- Main command -----------------------------------------------------------

_cmd_devcontainer() {
    init_project_dir "$PROJECT_DIR"

    local image_name
    image_name=$(get_image_name)

    # Verify the image exists
    if ! docker image inspect "$image_name" >/dev/null 2>&1; then
        error "No ClaudeBox image found for this project.\nRun 'claudebox' first to build the image, then re-run 'claudebox devcontainer'."
    fi

    local devcontainer_dir="$PROJECT_DIR/.devcontainer"
    local devcontainer_file="$devcontainer_dir/devcontainer.json"
    local vscode_dir="$PROJECT_DIR/.vscode"
    local tasks_file="$vscode_dir/tasks.json"
    local launch_file="$vscode_dir/launch.json"

    # Warn if devcontainer file already exists
    if [[ -f "$devcontainer_file" ]]; then
        cecho "Existing .devcontainer/devcontainer.json found." "$YELLOW"
        printf "Overwrite all generated configs? (y/n) "
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            printf '%s\n' "Aborted."
            exit 0
        fi
    fi

    mkdir -p "$devcontainer_dir"
    mkdir -p "$vscode_dir"

    # ---- Profiles & extensions ----
    local current_profiles=""
    _devcontainer_gather_profiles
    local extensions=""
    _devcontainer_build_extensions "$current_profiles"

    # ---- .devcontainer/devcontainer.json ----
    cat > "$devcontainer_file" << DEVEOF
// Generated by ClaudeBox (claudebox devcontainer)
// Image: ${image_name}
// Profiles: ${current_profiles:-none}
//
// Re-generate with:  claudebox devcontainer
{
    "name": "ClaudeBox - $(basename "$PROJECT_DIR")",
    "image": "${image_name}",
    "containerUser": "${DOCKER_USER}",
    "workspaceFolder": "/workspace",
    "workspaceMount": "source=\${localWorkspaceFolder},target=/workspace,type=bind",
    "remoteEnv": {
        "DEVCONTAINER": "true",
        "TERM": "xterm-256color",
        "NVM_DIR": "/home/${DOCKER_USER}/.nvm"
    },
    "mounts": [
        "source=\${localEnv:HOME}/.ssh,target=/home/${DOCKER_USER}/.ssh,type=bind,readonly"
    ],
    "customizations": {
        "vscode": {
            "settings": {
                "terminal.integrated.defaultProfile.linux": "zsh",
                "terminal.integrated.profiles.linux": {
                    "zsh": { "path": "/bin/zsh" },
                    "bash": { "path": "/bin/bash" }
                },
                "editor.formatOnSave": true,
                "files.trimTrailingWhitespace": true,
                "remote.autoForwardPorts": true
            },
            "extensions": [
        ${extensions}
            ]
        }
    },
    "postStartCommand": "bash -c 'git config --global --add safe.directory /workspace && source \$NVM_DIR/nvm.sh 2>/dev/null || true'",
    "overrideCommand": true
}
DEVEOF

    # ---- .vscode/tasks.json ----
    # Only write if file does not already exist (don't clobber user tasks)
    if [[ ! -f "$tasks_file" ]]; then
        _devcontainer_write_tasks "$tasks_file" "$current_profiles"
    fi

    # ---- .vscode/launch.json ----
    if [[ ! -f "$launch_file" ]]; then
        _devcontainer_write_launch "$launch_file" "$current_profiles"
    fi

    # ---- Output summary ----
    cecho "Generated VS Code integration files:" "$GREEN"
    printf '\n'
    printf "  %s\n" ".devcontainer/devcontainer.json"
    if [[ ! -f "$tasks_file" ]] || [[ -f "$tasks_file" ]]; then
        printf "  %s\n" ".vscode/tasks.json"
    fi
    if [[ ! -f "$launch_file" ]] || [[ -f "$launch_file" ]]; then
        printf "  %s\n" ".vscode/launch.json"
    fi
    printf '\n'
    printf "  Image:    %s\n" "$image_name"
    if [[ -n "$current_profiles" ]]; then
        printf "  Profiles: %s\n" "$current_profiles"
    fi
    printf '\n'
    cecho "To use:" "$CYAN"
    printf "  1. Open this folder in VS Code\n"
    printf "  2. Install the Dev Containers extension (ms-vscode-remote.remote-containers)\n"
    printf "  3. Cmd+Shift+P -> 'Dev Containers: Reopen in Container'\n"
    printf '\n'
    cecho "Available tasks (Terminal -> Run Task):" "$CYAN"
    printf "  Claude: Launch              Start Claude CLI interactively\n"
    printf "  Claude: Shell               Open zsh shell in container\n"
    printf "  Claude: Update              Update Claude CLI\n"
    printf "  ClaudeBox: Rebuild Image    Rebuild the Docker image\n"
    printf "  ClaudeBox: Show Info        Show project/system info\n"
    printf '\n'
}

# ---- tasks.json generator ---------------------------------------------------

_devcontainer_write_tasks() {
    local tasks_file="$1"
    local profiles="$2"

    # Build profile-specific tasks
    local extra_tasks=""

    if printf '%s' "$profiles" | grep -qw "python"; then
        extra_tasks="$extra_tasks,
        {
            \"label\": \"Python: Run File\",
            \"type\": \"shell\",
            \"command\": \"python \\\${file}\",
            \"group\": \"build\",
            \"presentation\": { \"reveal\": \"always\", \"panel\": \"shared\" },
            \"icon\": { \"id\": \"symbol-method\", \"color\": \"terminal.ansiYellow\" }
        },
        {
            \"label\": \"Python: Run Tests\",
            \"type\": \"shell\",
            \"command\": \"python -m pytest\",
            \"group\": \"test\",
            \"presentation\": { \"reveal\": \"always\", \"panel\": \"shared\" },
            \"icon\": { \"id\": \"beaker\", \"color\": \"terminal.ansiGreen\" }
        }"
    fi

    if printf '%s' "$profiles" | grep -qw "rust"; then
        extra_tasks="$extra_tasks,
        {
            \"label\": \"Rust: Build\",
            \"type\": \"shell\",
            \"command\": \"cargo build\",
            \"group\": \"build\",
            \"problemMatcher\": \"\$rustc\",
            \"icon\": { \"id\": \"gear\", \"color\": \"terminal.ansiRed\" }
        },
        {
            \"label\": \"Rust: Test\",
            \"type\": \"shell\",
            \"command\": \"cargo test\",
            \"group\": \"test\",
            \"problemMatcher\": \"\$rustc\",
            \"icon\": { \"id\": \"beaker\", \"color\": \"terminal.ansiRed\" }
        }"
    fi

    if printf '%s' "$profiles" | grep -qw "go"; then
        extra_tasks="$extra_tasks,
        {
            \"label\": \"Go: Build\",
            \"type\": \"shell\",
            \"command\": \"go build ./...\",
            \"group\": \"build\",
            \"icon\": { \"id\": \"gear\", \"color\": \"terminal.ansiCyan\" }
        },
        {
            \"label\": \"Go: Test\",
            \"type\": \"shell\",
            \"command\": \"go test ./...\",
            \"group\": \"test\",
            \"icon\": { \"id\": \"beaker\", \"color\": \"terminal.ansiCyan\" }
        }"
    fi

    if printf '%s' "$profiles" | grep -qw "javascript"; then
        extra_tasks="$extra_tasks,
        {
            \"label\": \"Node: Install\",
            \"type\": \"shell\",
            \"command\": \"npm install\",
            \"icon\": { \"id\": \"package\", \"color\": \"terminal.ansiGreen\" }
        },
        {
            \"label\": \"Node: Test\",
            \"type\": \"shell\",
            \"command\": \"npm test\",
            \"group\": \"test\",
            \"icon\": { \"id\": \"beaker\", \"color\": \"terminal.ansiGreen\" }
        }"
    fi

    if printf '%s' "$profiles" | grep -qw "java"; then
        extra_tasks="$extra_tasks,
        {
            \"label\": \"Java: Maven Build\",
            \"type\": \"shell\",
            \"command\": \"mvn package\",
            \"group\": \"build\",
            \"icon\": { \"id\": \"gear\", \"color\": \"terminal.ansiYellow\" }
        }"
    fi

    cat > "$tasks_file" << TASKEOF
// Generated by ClaudeBox (claudebox devcontainer)
// Re-generate with:  claudebox devcontainer
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Claude: Launch",
            "type": "shell",
            "command": "source \$NVM_DIR/nvm.sh && claude",
            "group": "none",
            "presentation": { "reveal": "always", "panel": "dedicated", "focus": true },
            "icon": { "id": "hubot", "color": "terminal.ansiMagenta" },
            "isBackground": false
        },
        {
            "label": "Claude: Shell",
            "type": "shell",
            "command": "/bin/zsh",
            "group": "none",
            "presentation": { "reveal": "always", "panel": "dedicated", "focus": true },
            "icon": { "id": "terminal", "color": "terminal.ansiBlue" }
        },
        {
            "label": "Claude: Update",
            "type": "shell",
            "command": "source \$NVM_DIR/nvm.sh && npm update -g @anthropic-ai/claude-code",
            "group": "none",
            "presentation": { "reveal": "always", "panel": "shared" },
            "icon": { "id": "cloud-download", "color": "terminal.ansiCyan" }
        },
        {
            "label": "ClaudeBox: Rebuild Image",
            "type": "shell",
            "command": "claudebox rebuild",
            "group": "none",
            "options": { "cwd": "\${workspaceFolder}" },
            "presentation": { "reveal": "always", "panel": "shared" },
            "icon": { "id": "refresh", "color": "terminal.ansiYellow" },
            "runOptions": { "runOn": "default" }
        },
        {
            "label": "ClaudeBox: Show Info",
            "type": "shell",
            "command": "claudebox info",
            "group": "none",
            "options": { "cwd": "\${workspaceFolder}" },
            "presentation": { "reveal": "always", "panel": "shared" },
            "icon": { "id": "info", "color": "terminal.ansiBlue" }
        }${extra_tasks}
    ]
}
TASKEOF
}

# ---- launch.json generator --------------------------------------------------

_devcontainer_write_launch() {
    local launch_file="$1"
    local profiles="$2"

    local configs=""

    # Python debug config
    if printf '%s' "$profiles" | grep -qw "python"; then
        configs="$configs
        {
            \"name\": \"Python: Current File\",
            \"type\": \"debugpy\",
            \"request\": \"launch\",
            \"program\": \"\${file}\",
            \"console\": \"integratedTerminal\"
        },"
    fi

    # Rust debug config
    if printf '%s' "$profiles" | grep -qw "rust"; then
        configs="$configs
        {
            \"name\": \"Rust: Debug Binary\",
            \"type\": \"cppdbg\",
            \"request\": \"launch\",
            \"program\": \"\${workspaceFolder}/target/debug/\${workspaceFolderBasename}\",
            \"args\": [],
            \"cwd\": \"\${workspaceFolder}\",
            \"MIDebuggerPath\": \"/usr/bin/gdb\"
        },"
    fi

    # Go debug config
    if printf '%s' "$profiles" | grep -qw "go"; then
        configs="$configs
        {
            \"name\": \"Go: Launch Package\",
            \"type\": \"go\",
            \"request\": \"launch\",
            \"mode\": \"auto\",
            \"program\": \"\${workspaceFolder}\"
        },"
    fi

    # Node debug config
    if printf '%s' "$profiles" | grep -qw "javascript"; then
        configs="$configs
        {
            \"name\": \"Node: Current File\",
            \"type\": \"node\",
            \"request\": \"launch\",
            \"program\": \"\${file}\",
            \"console\": \"integratedTerminal\",
            \"runtimeArgs\": [\"--nolazy\"]
        },"
    fi

    # C/C++ debug config
    if printf '%s' "$profiles" | grep -qE '(^|, )c(,|$)'; then
        configs="$configs
        {
            \"name\": \"C/C++: Debug Active File\",
            \"type\": \"cppdbg\",
            \"request\": \"launch\",
            \"program\": \"\${fileDirname}/\${fileBasenameNoExtension}\",
            \"args\": [],
            \"cwd\": \"\${workspaceFolder}\",
            \"preLaunchTask\": \"C/C++: gcc build active file\",
            \"MIDebuggerPath\": \"/usr/bin/gdb\"
        },"
    fi

    # Java debug config
    if printf '%s' "$profiles" | grep -qw "java"; then
        configs="$configs
        {
            \"name\": \"Java: Current File\",
            \"type\": \"java\",
            \"request\": \"launch\",
            \"mainClass\": \"\${file}\"
        },"
    fi

    # Flutter
    if printf '%s' "$profiles" | grep -qw "flutter"; then
        configs="$configs
        {
            \"name\": \"Flutter: Run\",
            \"type\": \"dart\",
            \"request\": \"launch\",
            \"program\": \"lib/main.dart\"
        },"
    fi

    # Strip trailing comma from last config
    configs=$(printf '%s' "$configs" | sed '$ s/,$//')

    # Only write if we have configs
    if [[ -z "$configs" ]]; then
        configs="
        {
            \"name\": \"Attach to Process\",
            \"type\": \"node\",
            \"request\": \"attach\",
            \"port\": 9229
        }"
    fi

    cat > "$launch_file" << LAUNCHEOF
// Generated by ClaudeBox (claudebox devcontainer)
// Re-generate with:  claudebox devcontainer
{
    "version": "0.2.0",
    "configurations": [${configs}
    ]
}
LAUNCHEOF
}

export -f _cmd_devcontainer _devcontainer_build_extensions _devcontainer_gather_profiles _devcontainer_write_tasks _devcontainer_write_launch
